version: '3.8'
services:
 model:
    build: ./Models
    volumes:
      - model_volume:/Models
    ports:
      - "5000:5000"

 streamlit_app:
    build: ./StreamlitApp
    volumes:
      - model_volume:/Models
      - streamlit_volume:/StreamlitApp
    ports:
      - "8501:8501"
    depends_on:
      - Models

volumes:
 model_volume:
 streamlit_volume: