version: '3.8'
services:
 models:
    build: ./models
    volumes:
      - model_volume:/models
    ports:
      - "5000:5000"

 StreamlitApp:
    build: ./streamlit_app
    volumes:
      - model_volume:/models
      - streamlit_volume:/streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - models

volumes:
 model_volume:
 streamlit_volume: